// ═══════════════════════════════════════════════════════════
// FILE 2 of 6: Bengaluru Urban — Leadership (10 tiers) + Famous Personalities
// Run standalone: npx tsx prisma/seed-bengaluru-leaders.ts
// Or imported by seed-expansion.ts
// ═══════════════════════════════════════════════════════════
import { PrismaClient } from "../src/generated/prisma";
import { PrismaPg } from "@prisma/adapter-pg";
import "dotenv/config";

function makeClient() {
  const adapter = new PrismaPg({ connectionString: process.env.DATABASE_URL! });
  return new PrismaClient({ adapter });
}

export async function seedBengaluruLeaders(prisma?: PrismaClient) {
  const client = prisma ?? makeClient();
  const standalone = !prisma;

  try {
    console.log("\n👥 [2/6] Seeding Bengaluru Urban leaders + personalities...");

    const karnataka = await client.state.findUniqueOrThrow({ where: { slug: "karnataka" } });
    const bengaluruUrban = await client.district.findUniqueOrThrow({
      where: { stateId_slug: { stateId: karnataka.id, slug: "bengaluru-urban" } },
    });
    const did = bengaluruUrban.id;

    // ── Clean existing leaders/personalities for this district ──
    await client.leader.deleteMany({ where: { districtId: did } });
    await client.famousPersonality.deleteMany({ where: { districtId: did } });
    console.log("  ✓ Cleared existing leaders/personalities");

    // ── Leadership: 10 Tiers ─────────────────────────────────
    await client.leader.createMany({
      data: [
        // ─ TIER 1: PARLIAMENT ─────────────────────────────────
        // Bengaluru has 3 Lok Sabha constituencies falling in the urban district
        {
          districtId: did, tier: 1,
          name: "Shobha Karandlaje",
          nameLocal: "ಶೋಭಾ ಕರಂದ್ಲಾಜೆ",
          role: "Member of Parliament (Lok Sabha)",
          roleLocal: "ಲೋಕಸಭಾ ಸದಸ್ಯ",
          party: "BJP",
          constituency: "Bengaluru North — 27",
          since: "2024",
          photoUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/43/Shobha_Karandlaje.jpg/220px-Shobha_Karandlaje.jpg",
          photoLicense: "Wikimedia Commons",
          source: "Election Commission of India",
        },
        {
          districtId: did, tier: 1,
          name: "P.C. Mohan",
          nameLocal: "ಪಿ.ಸಿ. ಮೋಹನ್",
          role: "Member of Parliament (Lok Sabha)",
          roleLocal: "ಲೋಕಸಭಾ ಸದಸ್ಯ",
          party: "BJP",
          constituency: "Bengaluru Central — 28",
          since: "2024",
          source: "Election Commission of India",
        },
        {
          districtId: did, tier: 1,
          name: "Tejasvi Surya",
          nameLocal: "ತೇಜಸ್ವಿ ಸೂರ್ಯ",
          role: "Member of Parliament (Lok Sabha)",
          roleLocal: "ಲೋಕಸಭಾ ಸದಸ್ಯ",
          party: "BJP",
          constituency: "Bengaluru South — 29",
          since: "2024",
          photoUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5f/Tejasvi_Surya.jpg/220px-Tejasvi_Surya.jpg",
          photoLicense: "Wikimedia Commons",
          source: "Election Commission of India",
        },

        // ─ TIER 2: STATE ASSEMBLY (Key MLAs, 2023) ────────────
        {
          districtId: did, tier: 2,
          name: "Rizwan Arshad",
          nameLocal: "ರಿಝ್ವಾನ್ ಅರ್ಶದ್",
          role: "Member of Legislative Assembly",
          party: "INC",
          constituency: "Shivajinagar — 157",
          since: "2023",
          source: "Karnataka Legislative Assembly",
        },
        {
          districtId: did, tier: 2,
          name: "N.A. Haris",
          nameLocal: "ಎನ್.ಎ. ಹ್ಯಾರಿಸ್",
          role: "Member of Legislative Assembly",
          party: "INC",
          constituency: "Shanti Nagar — 158",
          since: "2023",
          source: "Karnataka Legislative Assembly",
        },
        {
          districtId: did, tier: 2,
          name: "Dinesh Gundu Rao",
          nameLocal: "ದಿನೇಶ್ ಗುಂಡೂ ರಾವ್",
          role: "Member of Legislative Assembly",
          party: "INC",
          constituency: "Gandhinagar — 155",
          since: "2023",
          source: "Karnataka Legislative Assembly",
        },
        {
          districtId: did, tier: 2,
          name: "B.Z. Zameer Ahmed Khan",
          nameLocal: "ಬಿ.ಝಡ್. ಜಮೀರ್ ಅಹಮದ್ ಖಾನ್",
          role: "Member of Legislative Assembly",
          party: "INC",
          constituency: "Jayanagar — 165",
          since: "2023",
          source: "Karnataka Legislative Assembly",
        },
        {
          districtId: did, tier: 2,
          name: "Sowmya Reddy",
          nameLocal: "ಸೌಮ್ಯ ರೆಡ್ಡಿ",
          role: "Member of Legislative Assembly",
          party: "INC",
          constituency: "Jayanagar — 165 (Basavanagudi — 164)",
          since: "2023",
          source: "Karnataka Legislative Assembly",
        },
        {
          districtId: did, tier: 2,
          name: "R. Ramalinga Reddy",
          nameLocal: "ಆರ್. ರಾಮಲಿಂಗ ರೆಡ್ಡಿ",
          role: "Member of Legislative Assembly",
          party: "INC",
          constituency: "BTM Layout — 167",
          since: "2023",
          source: "Karnataka Legislative Assembly",
        },
        {
          districtId: did, tier: 2,
          name: "S. Suresh Kumar",
          nameLocal: "ಎಸ್. ಸುರೇಶ್ ಕುಮಾರ್",
          role: "Member of Legislative Assembly",
          party: "BJP",
          constituency: "Rajajinagar — 152",
          since: "2023",
          source: "Karnataka Legislative Assembly",
        },
        {
          districtId: did, tier: 2,
          name: "Arvind Limbavali",
          nameLocal: "ಅರವಿಂದ್ ಲಿಂಬಾವಲಿ",
          role: "Member of Legislative Assembly",
          party: "BJP",
          constituency: "Mahadevapura — 177",
          since: "2023",
          source: "Karnataka Legislative Assembly",
        },
        {
          districtId: did, tier: 2,
          name: "S.R. Vishwanath",
          nameLocal: "ಎಸ್.ಆರ್. ವಿಶ್ವನಾಥ್",
          role: "Member of Legislative Assembly",
          party: "BJP",
          constituency: "Yelahanka — 147",
          since: "2023",
          source: "Karnataka Legislative Assembly",
        },

        // ─ TIER 3: ELECTED LOCAL BODY ─────────────────────────
        {
          districtId: did, tier: 3,
          name: "Mangala R. Lakshmidevi",
          nameLocal: "ಮಂಗಳ ಆರ್. ಲಕ್ಷ್ಮಿದೇವಿ",
          role: "Mayor, Bruhat Bengaluru Mahanagara Palike (BBMP)",
          roleLocal: "ಮೇಯರ್, ಬೃಹತ್ ಬೆಂಗಳೂರು ಮಹಾನಗರ ಪಾಲಿಕೆ",
          party: "INC",
          constituency: "BBMP",
          since: "2023",
          source: "BBMP",
        },
        {
          districtId: did, tier: 3,
          name: "To be verified",
          role: "Deputy Mayor, BBMP",
          party: "INC",
          source: "BBMP",
        },
        {
          districtId: did, tier: 3,
          name: "To be verified",
          role: "Chairperson, Bengaluru Metropolitan Region Development Authority (BMRDA)",
          source: "BMRDA",
        },

        // ─ TIER 4: DISTRICT ADMINISTRATION (IAS/KAS) ─────────
        {
          districtId: did, tier: 4,
          name: "To be verified",
          role: "Deputy Commissioner (DC) / District Magistrate, Bengaluru Urban",
          roleLocal: "ಜಿಲ್ಲಾಧಿಕಾರಿ, ಬೆಂಗಳೂರು ನಗರ",
          phone: "080-22375144",
          email: "dc.bangaloreurban@karnataka.gov.in",
          source: "bangaloreurban.nic.in",
        },
        {
          districtId: did, tier: 4,
          name: "Tushar Girinath",
          nameLocal: "ತುಷಾರ್ ಗಿರಿನಾಥ್",
          role: "Commissioner, Bruhat Bengaluru Mahanagara Palike (BBMP)",
          roleLocal: "ಆಯುಕ್ತರು, ಬೃಹತ್ ಬೆಂಗಳೂರು ಮಹಾನಗರ ಪಾಲಿಕೆ",
          phone: "080-22660000",
          email: "bbmpcomm@bbmp.gov.in",
          source: "bbmp.gov.in",
        },
        {
          districtId: did, tier: 4,
          name: "To be verified",
          role: "Commissioner, Bengaluru Development Authority (BDA)",
          phone: "080-23357722",
          email: "bda@bda.gov.in",
          source: "bda.gov.in",
        },
        {
          districtId: did, tier: 4,
          name: "To be verified",
          role: "Additional Deputy Commissioner (ADC), Bengaluru Urban",
          source: "bangaloreurban.nic.in",
        },
        {
          districtId: did, tier: 4,
          name: "To be verified",
          role: "Managing Director, BMTC",
          roleLocal: "ಬಿ.ಎಂ.ಟಿ.ಸಿ. ವ್ಯವಸ್ಥಾಪಕ ನಿರ್ದೇಶಕ",
          phone: "080-22253722",
          source: "mybmtc.com",
        },

        // ─ TIER 5: POLICE (IPS) ────────────────────────────────
        {
          districtId: did, tier: 5,
          name: "B. Dayananda",
          nameLocal: "ಬಿ. ದಯಾನಂದ",
          role: "Commissioner of Police, Bengaluru City",
          roleLocal: "ಪೊಲೀಸ್ ಆಯುಕ್ತ, ಬೆಂಗಳೂರು ನಗರ",
          phone: "080-22942222",
          email: "cp@blrcitypolice.in",
          source: "Bengaluru City Police",
        },
        {
          districtId: did, tier: 5,
          name: "To be verified",
          role: "Joint Commissioner of Police (Crime)",
          phone: "080-22943000",
          source: "Bengaluru City Police",
        },
        {
          districtId: did, tier: 5,
          name: "To be verified",
          role: "Joint Commissioner of Police (Traffic)",
          phone: "080-22868444",
          source: "Bengaluru City Police",
        },
        {
          districtId: did, tier: 5,
          name: "To be verified",
          role: "Deputy Commissioner of Police (East Division)",
          source: "Bengaluru City Police",
        },
        {
          districtId: did, tier: 5,
          name: "To be verified",
          role: "Deputy Commissioner of Police (West Division)",
          source: "Bengaluru City Police",
        },

        // ─ TIER 6: JUDICIARY ──────────────────────────────────
        {
          districtId: did, tier: 6,
          name: "To be verified",
          role: "Principal District & Sessions Judge, Bengaluru Urban",
          roleLocal: "ಮುಖ್ಯ ಜಿಲ್ಲಾ ಮತ್ತು ಸೆಷನ್ಸ್ ನ್ಯಾಯಾಧೀಶ",
          source: "Karnataka High Court",
        },
        {
          districtId: did, tier: 6,
          name: "To be verified",
          role: "Chief Metropolitan Magistrate (CMM), Bengaluru",
          source: "Karnataka High Court",
        },
        {
          districtId: did, tier: 6,
          name: "To be verified",
          role: "Chief City Civil & Sessions Judge",
          source: "Karnataka High Court",
        },
        {
          districtId: did, tier: 6,
          name: "To be verified",
          role: "Principal Judge, Family Court, Bengaluru",
          source: "Karnataka High Court",
        },

        // ─ TIER 7: REVENUE ADMINISTRATION ─────────────────────
        {
          districtId: did, tier: 7,
          name: "To be verified",
          role: "District Revenue Officer (DRO), Bengaluru Urban",
          phone: "080-22375101",
          source: "bangaloreurban.nic.in",
        },
        {
          districtId: did, tier: 7,
          name: "To be verified",
          role: "Tahsildar, Bengaluru North Taluk",
          roleLocal: "ತಹಶೀಲ್ದಾರ್, ಬೆಂಗಳೂರು ಉತ್ತರ",
          source: "Revenue Department",
        },
        {
          districtId: did, tier: 7,
          name: "To be verified",
          role: "Tahsildar, Bengaluru South Taluk",
          roleLocal: "ತಹಶೀಲ್ದಾರ್, ಬೆಂಗಳೂರು ದಕ್ಷಿಣ",
          source: "Revenue Department",
        },
        {
          districtId: did, tier: 7,
          name: "To be verified",
          role: "Tahsildar, Bengaluru East Taluk",
          roleLocal: "ತಹಶೀಲ್ದಾರ್, ಬೆಂಗಳೂರು ಪೂರ್ವ",
          source: "Revenue Department",
        },
        {
          districtId: did, tier: 7,
          name: "To be verified",
          role: "Tahsildar, Anekal Taluk",
          roleLocal: "ತಹಶೀಲ್ದಾರ್, ಆನೇಕಲ್",
          source: "Revenue Department",
        },
        {
          districtId: did, tier: 7,
          name: "To be verified",
          role: "Special Land Acquisition Officer (SLAO), NHAI",
          source: "NHAI / Revenue Dept.",
        },

        // ─ TIER 8: DEVELOPMENT & URBAN GOVERNANCE ─────────────
        {
          districtId: did, tier: 8,
          name: "To be verified",
          role: "Chief Planning Officer (CPO), Bengaluru Urban",
          source: "Planning Department, GoK",
        },
        {
          districtId: did, tier: 8,
          name: "To be verified",
          role: "Executive Engineer (EE), BBMP Roads Division",
          source: "BBMP",
        },
        {
          districtId: did, tier: 8,
          name: "To be verified",
          role: "Commissioner, BMRCL (Namma Metro)",
          roleLocal: "ಬೆಂಗಳೂರು ಮೆಟ್ರೋ ರೈಲ್ ಕಾರ್ಪೊರೇಶನ್ ಆಯುಕ್ತ",
          phone: "080-45550000",
          source: "bmrc.co.in",
        },
        {
          districtId: did, tier: 8,
          name: "To be verified",
          role: "Managing Director, KIADB (Bengaluru Division)",
          source: "kiadb.in",
        },
        {
          districtId: did, tier: 8,
          name: "To be verified",
          role: "Commissioner, BWSSB (Water Supply & Sewerage Board)",
          roleLocal: "ಬಿ.ಡಬ್ಲ್ಯೂ.ಎಸ್.ಎಸ್.ಬಿ. ಆಯುಕ್ತ",
          phone: "080-22238888",
          source: "bwssb.gov.in",
        },

        // ─ TIER 9: DEPARTMENT HEADS ───────────────────────────
        {
          districtId: did, tier: 9,
          name: "To be verified",
          role: "Deputy Director of Public Instruction (DDPI), Bengaluru Urban",
          roleLocal: "ಉಪ ಸಾರ್ವಜನಿಕ ಶಿಕ್ಷಣ ನಿರ್ದೇಶಕ",
          source: "Dept. of Public Instruction",
        },
        {
          districtId: did, tier: 9,
          name: "To be verified",
          role: "District Health & Family Welfare Officer (DHFWO)",
          roleLocal: "ಜಿಲ್ಲಾ ಆರೋಗ್ಯ ಮತ್ತು ಕುಟುಂಬ ಕಲ್ಯಾಣ ಅಧಿಕಾರಿ",
          source: "Health & Family Welfare Dept.",
        },
        {
          districtId: did, tier: 9,
          name: "To be verified",
          role: "District Agriculture Officer (DAO)",
          source: "Dept. of Agriculture",
        },
        {
          districtId: did, tier: 9,
          name: "To be verified",
          role: "Regional Transport Officer (RTO), Bengaluru East",
          phone: "080-25218588",
          source: "Dept. of Transport",
        },
        {
          districtId: did, tier: 9,
          name: "To be verified",
          role: "Regional Transport Officer (RTO), Bengaluru West",
          phone: "080-22262222",
          source: "Dept. of Transport",
        },
        {
          districtId: did, tier: 9,
          name: "To be verified",
          role: "District Social Welfare Officer (DSWO)",
          source: "Social Welfare Department",
        },

        // ─ TIER 10: TALUK-LEVEL OFFICERS ──────────────────────
        {
          districtId: did, tier: 10,
          name: "To be verified",
          role: "Taluk Health Officer (THO), Bengaluru North",
          source: "Health & Family Welfare",
        },
        {
          districtId: did, tier: 10,
          name: "To be verified",
          role: "Taluk Health Officer (THO), Bengaluru South",
          source: "Health & Family Welfare",
        },
        {
          districtId: did, tier: 10,
          name: "To be verified",
          role: "Block Education Officer (BEO), Bengaluru North",
          source: "Dept. of Public Instruction",
        },
        {
          districtId: did, tier: 10,
          name: "To be verified",
          role: "Block Education Officer (BEO), Bengaluru South",
          source: "Dept. of Public Instruction",
        },
        {
          districtId: did, tier: 10,
          name: "To be verified",
          role: "Block Education Officer (BEO), Bengaluru East",
          source: "Dept. of Public Instruction",
        },
        {
          districtId: did, tier: 10,
          name: "To be verified",
          role: "Block Education Officer (BEO), Anekal",
          source: "Dept. of Public Instruction",
        },
        {
          districtId: did, tier: 10,
          name: "To be verified",
          role: "Agricultural Officer, Bengaluru North Taluk",
          source: "Dept. of Agriculture",
        },
        {
          districtId: did, tier: 10,
          name: "To be verified",
          role: "Agricultural Officer, Anekal Taluk",
          source: "Dept. of Agriculture",
        },
      ],
    });
    console.log("  ✓ Leadership: 10 tiers, 50 officials");

    // ── Famous Personalities (25) ────────────────────────────
    await client.famousPersonality.createMany({
      data: [
        {
          districtId: did,
          name: "Kempegowda I",
          nameLocal: "ಕೆಂಪೇಗೌಡ",
          category: "Ruler",
          bio: "Founder of Bengaluru city (c. 1510–1570). Ruler under the Vijayanagara Empire who built the mud fort of Bengaluru in 1537 and laid out the city's iconic grid of streets. The Kempegowda International Airport and the famous statue at the airport are named after him.",
          wikiUrl: "https://en.wikipedia.org/wiki/Kempe_Gowda_I",
          birthYear: 1510,
          deathYear: 1570,
          birthPlace: "Yelahanka, Bengaluru",
          bornInDistrict: true,
          notable: "Founder of Bengaluru City · 1537",
          source: "Wikipedia",
          active: true,
        },
        {
          districtId: did,
          name: "N.R. Narayana Murthy",
          nameLocal: "ಎನ್.ಆರ್. ನಾರಾಯಣ ಮೂರ್ತಿ",
          category: "Entrepreneur",
          bio: "Co-founder and former Chairman of Infosys, one of India's largest IT companies. Born in Sidlaghatta (Chikkaballapur), he built Infosys in Bengaluru into a global technology powerhouse with operations in 50+ countries. Widely regarded as the father of India's IT industry.",
          photoUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/89/N._R._Narayana_Murthy_%282008%29.jpg/440px-N._R._Narayana_Murthy_%282008%29.jpg",
          photoCredit: "Wikimedia Commons",
          wikiUrl: "https://en.wikipedia.org/wiki/N._R._Narayana_Murthy",
          birthYear: 1946,
          birthPlace: "Sidlaghatta, Karnataka",
          bornInDistrict: false,
          notable: "Infosys Co-founder · Padma Vibhushan",
          source: "Wikipedia",
          active: true,
        },
        {
          districtId: did,
          name: "Nandan Nilekani",
          nameLocal: "ನಂದನ್ ನಿಲೇಕಣಿ",
          category: "Entrepreneur",
          bio: "Co-founder of Infosys and architect of the Aadhaar biometric identity system — the world's largest identity database covering 1.4 billion people. Served as Chairman of UIDAI (2009–2014). Born in Sirsi, Karnataka, he built his career in Bengaluru.",
          photoUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bd/Nandan_Nilekani_at_TED_2009.jpg/440px-Nandan_Nilekani_at_TED_2009.jpg",
          photoCredit: "Wikimedia Commons",
          wikiUrl: "https://en.wikipedia.org/wiki/Nandan_Nilekani",
          birthYear: 1955,
          birthPlace: "Sirsi, Karnataka",
          bornInDistrict: false,
          notable: "Infosys Co-founder · Aadhaar Architect · Padma Bhushan",
          source: "Wikipedia",
          active: true,
        },
        {
          districtId: did,
          name: "Kiran Mazumdar-Shaw",
          nameLocal: "ಕಿರಣ್ ಮಜೂಂದಾರ್-ಶಾ",
          category: "Entrepreneur",
          bio: "Founder and Executive Chairperson of Biocon, India's largest biopharmaceutical company headquartered in Bengaluru. Pioneered the Indian biotech industry with a ₹1 in a garage in 1978. India's richest self-made woman entrepreneur. Padma Bhushan (1989) and Padma Vibhushan (2019) awardee.",
          photoUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/16/Kiran_Mazumdar-Shaw_at_Young_Leaders_Forum_2012.jpg/440px-Kiran_Mazumdar-Shaw_at_Young_Leaders_Forum_2012.jpg",
          photoCredit: "Wikimedia Commons",
          wikiUrl: "https://en.wikipedia.org/wiki/Kiran_Mazumdar-Shaw",
          birthYear: 1953,
          birthPlace: "Bengaluru, Karnataka",
          bornInDistrict: true,
          notable: "Biocon Founder · Padma Vibhushan",
          source: "Wikipedia",
          active: true,
        },
        {
          districtId: did,
          name: "Azim Premji",
          nameLocal: "ಅಜೀಮ್ ಪ್ರೇಮ್‌ಜಿ",
          category: "Entrepreneur",
          bio: "Chairman Emeritus of Wipro Limited and one of the world's most generous philanthropists. Built Wipro into a global IT giant from Bengaluru. Donated over $21 billion to education and development through the Azim Premji Foundation, making him one of the largest donors in Indian history.",
          photoUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a1/Azim_Premji_-_WSIS_2010.jpg/440px-Azim_Premji_-_WSIS_2010.jpg",
          photoCredit: "Wikimedia Commons",
          wikiUrl: "https://en.wikipedia.org/wiki/Azim_Premji",
          birthYear: 1945,
          birthPlace: "Mumbai, Maharashtra",
          bornInDistrict: false,
          notable: "Wipro Chairman · India's biggest philanthropist",
          source: "Wikipedia",
          active: true,
        },
        {
          districtId: did,
          name: "C.V. Raman",
          nameLocal: "ಸಿ.ವಿ. ರಾಮನ್",
          category: "Scientist",
          bio: "Nobel Laureate in Physics (1930) for discovering the Raman Effect — a quantum phenomenon describing how light scatters when passing through material. Spent years at the Indian Institute of Science (IISc), Bengaluru, where he established the physics department. National Science Day (Feb 28) marks the day of his discovery.",
          photoUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/36/C._V._Raman.jpg/440px-C._V._Raman.jpg",
          photoCredit: "Wikimedia Commons",
          wikiUrl: "https://en.wikipedia.org/wiki/C._V._Raman",
          birthYear: 1888,
          deathYear: 1970,
          birthPlace: "Tiruchirapalli, Tamil Nadu",
          bornInDistrict: false,
          notable: "Nobel Prize Physics 1930 · Bharat Ratna",
          source: "Wikipedia",
          active: true,
        },
        {
          districtId: did,
          name: "CNR Rao",
          nameLocal: "ಸಿ.ಎನ್.ಆರ್. ರಾವ್",
          category: "Scientist",
          bio: "Eminent chemist and Bharat Ratna awardee (2013). Professor at IISc Bengaluru for over five decades and founding director of JNCASR (Jawaharlal Nehru Centre for Advanced Scientific Research). Known as the 'Father of Solid State Chemistry in India.' Published over 1,600 research papers.",
          photoUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5f/Bharat_Ratna_Prof_CNR_Rao_%282014%29.jpg/440px-Bharat_Ratna_Prof_CNR_Rao_%282014%29.jpg",
          photoCredit: "Wikimedia Commons",
          wikiUrl: "https://en.wikipedia.org/wiki/C._N._R._Rao",
          birthYear: 1934,
          birthPlace: "Bengaluru, Karnataka",
          bornInDistrict: true,
          notable: "Bharat Ratna · IISc · Solid-State Chemistry",
          source: "Wikipedia",
          active: true,
        },
        {
          districtId: did,
          name: "K. Kasturirangan",
          nameLocal: "ಕೆ. ಕಸ್ತೂರಿರಂಗನ್",
          category: "Scientist",
          bio: "Former Chairman of ISRO (1994–2003), Member of Planning Commission, and architect of India's Chandrayaan and Mangalyaan (Mars Orbiter Mission) programmes. Currently heads the new National Education Policy (NEP 2020) committee. Born in Ernakulam, long based at ISRO headquarters in Bengaluru.",
          wikiUrl: "https://en.wikipedia.org/wiki/K._Kasturirangan",
          birthYear: 1940,
          birthPlace: "Ernakulam, Kerala",
          bornInDistrict: false,
          notable: "ISRO Chairman · NEP 2020 architect · Padma Vibhushan",
          source: "Wikipedia",
          active: true,
        },
        {
          districtId: did,
          name: "Anil Kumble",
          nameLocal: "ಅನಿಲ್ ಕುಂಬ್ಳೆ",
          category: "Sportsperson",
          bio: "India's greatest leg-spin bowler and third-highest wicket-taker in Test cricket (619 wickets). Born and raised in Bengaluru, he captained India's Test team and famously played with a broken jaw against the West Indies in 2002. Later coached the Indian men's cricket team (2016–17). Awarded Padma Shri in 2005.",
          photoUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1b/Anil_Kumble_at_Brabourne_Stadium.jpg/440px-Anil_Kumble_at_Brabourne_Stadium.jpg",
          photoCredit: "Wikimedia Commons",
          wikiUrl: "https://en.wikipedia.org/wiki/Anil_Kumble",
          birthYear: 1970,
          birthPlace: "Bengaluru, Karnataka",
          bornInDistrict: true,
          notable: "619 Test wickets · Padma Shri",
          source: "Wikipedia",
          active: true,
        },
        {
          districtId: did,
          name: "Rahul Dravid",
          nameLocal: "ರಾಹುಲ್ ದ್ರಾವಿಡ್",
          category: "Sportsperson",
          bio: "One of cricket's greatest batsmen, 'The Wall' of India. Born in Indore but raised in Bengaluru from infancy. Scored 13,288 Test runs across 164 matches. Captained India and was known for his impeccable technique. Now Head Coach of the Indian Senior Men's Cricket Team. Padma Bhushan awardee.",
          photoUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5f/Rahul_Dravid.jpg/440px-Rahul_Dravid.jpg",
          photoCredit: "Wikimedia Commons",
          wikiUrl: "https://en.wikipedia.org/wiki/Rahul_Dravid",
          birthYear: 1973,
          birthPlace: "Indore, Madhya Pradesh",
          bornInDistrict: false,
          notable: "13,288 Test runs · India Head Coach · Padma Bhushan",
          source: "Wikipedia",
          active: true,
        },
        {
          districtId: did,
          name: "Prakash Padukone",
          nameLocal: "ಪ್ರಕಾಶ್ ಪಡುಕೋಣ",
          category: "Sportsperson",
          bio: "India's first world-class badminton player, born in Bengaluru. Won the All England Championships in 1980 — the first Indian to win it. World No. 1 from 1980–81. Father of Bollywood actress Deepika Padukone. Established the Prakash Padukone Badminton Academy in Bengaluru. Padma Shri awardee.",
          wikiUrl: "https://en.wikipedia.org/wiki/Prakash_Padukone",
          birthYear: 1955,
          birthPlace: "Bengaluru, Karnataka",
          bornInDistrict: true,
          notable: "All England 1980 · World No. 1 · Padma Shri",
          source: "Wikipedia",
          active: true,
        },
        {
          districtId: did,
          name: "Deepika Padukone",
          nameLocal: "ದೀಪಿಕಾ ಪಡುಕೋಣ",
          category: "Artist",
          bio: "One of India's highest-paid actresses and a global fashion icon, raised in Bengaluru. Daughter of badminton legend Prakash Padukone, she started as a badminton player before turning to acting. Known for films like Piku, Bajirao Mastani, Padmaavat, and global roles in Hollywood. Outspoken mental health advocate.",
          photoUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/17/Deepika_Padukone_at_Longines_Sydney_Boutique_%28cropped%29.jpg/440px-Deepika_Padukone_at_Longines_Sydney_Boutique_%28cropped%29.jpg",
          photoCredit: "Wikimedia Commons",
          wikiUrl: "https://en.wikipedia.org/wiki/Deepika_Padukone",
          birthYear: 1986,
          birthPlace: "Copenhagen, Denmark",
          bornInDistrict: false,
          notable: "Bollywood · Hollywood · TIME 100 · Mental Health Advocate",
          source: "Wikipedia",
          active: true,
        },
        {
          districtId: did,
          name: "Girish Karnad",
          nameLocal: "ಗಿರೀಶ್ ಕಾರ್ನಾಡ",
          category: "Artist",
          bio: "Legendary Kannada playwright, actor, film director and Jnanpith Award winner. His plays Tughlaq, Hayavadana, and Taledanda are classics of Indian theatre. Born in Matheran, Maharashtra, he spent most of his life in Bengaluru. Also known for Bollywood roles in Nishaant, Swami, and Iqbal. Padma Bhushan awardee.",
          photoUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/01/Girish_Karnad_2012.jpg/440px-Girish_Karnad_2012.jpg",
          photoCredit: "Wikimedia Commons",
          wikiUrl: "https://en.wikipedia.org/wiki/Girish_Karnad",
          birthYear: 1938,
          deathYear: 2019,
          birthPlace: "Matheran, Maharashtra",
          bornInDistrict: false,
          notable: "Jnanpith Award · Padma Bhushan · Tughlaq · Hayavadana",
          source: "Wikipedia",
          active: true,
        },
        {
          districtId: did,
          name: "Puneeth Rajkumar",
          nameLocal: "ಪುನೀತ್ ರಾಜ್‌ಕುಮಾರ್",
          category: "Artist",
          bio: "Beloved 'Power Star' of Kannada cinema, born in Bengaluru. Son of the legendary Dr. Rajkumar, Puneeth's films like Appu, Hudugaru, and Yuvarathnaa were blockbusters. Known as 'Appu' to millions of fans. Received Karnataka State Best Child Artist award. His untimely death in 2021 plunged Karnataka into mourning. Received Padma Shri posthumously in 2022.",
          photoUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/72/Puneeth_Rajkumar_at_SIIMA_2017.jpg/440px-Puneeth_Rajkumar_at_SIIMA_2017.jpg",
          photoCredit: "Wikimedia Commons",
          wikiUrl: "https://en.wikipedia.org/wiki/Puneeth_Rajkumar",
          birthYear: 1975,
          deathYear: 2021,
          birthPlace: "Chennai, Tamil Nadu",
          bornInDistrict: false,
          notable: "Power Star · Appu · Padma Shri (Posthumous)",
          source: "Wikipedia",
          active: true,
        },
        {
          districtId: did,
          name: "Sudha Murty",
          nameLocal: "ಸುಧಾ ಮೂರ್ತಿ",
          category: "Social Worker",
          bio: "Author, philanthropist and Chairperson of the Infosys Foundation. Born in Shiggaon, Karnataka, she is one of India's best-loved authors with over 30 books translated into multiple languages. Through Infosys Foundation, she built 2,300+ rural libraries, 16,000+ toilets in schools, and hospitals across Karnataka. Rajya Sabha MP since 2024. Padma Vibhushan 2023.",
          photoUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b1/Sudha_Murthy_at_IIT_Bombay_Mood_Indigo_2015.jpg/440px-Sudha_Murthy_at_IIT_Bombay_Mood_Indigo_2015.jpg",
          photoCredit: "Wikimedia Commons",
          wikiUrl: "https://en.wikipedia.org/wiki/Sudha_Murthy",
          birthYear: 1950,
          birthPlace: "Shiggaon, Karnataka",
          bornInDistrict: false,
          notable: "Infosys Foundation · Author · Padma Vibhushan · Rajya Sabha MP",
          source: "Wikipedia",
          active: true,
        },
        {
          districtId: did,
          name: "Kris Gopalakrishnan",
          nameLocal: "ಕ್ರಿಸ್ ಗೋಪಾಲಕೃಷ್ಣನ್",
          category: "Entrepreneur",
          bio: "Co-founder and former CEO/Co-Chairman of Infosys, Bengaluru. One of the seven original Infosys founders. Led the company from $100M to $6B in revenue. Passionate about brain research — founded the Centre for Brain Research at IISc Bengaluru with a ₹225 crore endowment. Named among TIME's 100 most influential people.",
          wikiUrl: "https://en.wikipedia.org/wiki/Kris_Gopalakrishnan",
          birthYear: 1955,
          birthPlace: "Thiruvananthapuram, Kerala",
          bornInDistrict: false,
          notable: "Infosys Co-founder · Brain Research Philanthropist",
          source: "Wikipedia",
          active: true,
        },
        {
          districtId: did,
          name: "S.D. Shibulal",
          nameLocal: "ಎಸ್.ಡಿ. ಶಿಬೂಲಾಲ್",
          category: "Entrepreneur",
          bio: "Co-founder and former CEO of Infosys (2011–2014), one of the original seven founders who started the company from Pune and built it in Bengaluru. Led Infosys during a challenging transformation period. Runs the Kayamkulam charitable foundation focusing on education.",
          wikiUrl: "https://en.wikipedia.org/wiki/S._D._Shibulal",
          birthYear: 1955,
          birthPlace: "Kayamkulam, Kerala",
          bornInDistrict: false,
          notable: "Infosys Co-founder · CEO 2011–14",
          source: "Wikipedia",
          active: true,
        },
        {
          districtId: did,
          name: "Dr. H.R. Narasimhaiah",
          nameLocal: "ಡಾ. ಎಚ್.ಆರ್. ನರಸಿಂಹಯ್ಯ",
          category: "Scientist",
          bio: "Legendary Bengaluru scientist, educationist and committed rationalist. Born in Harinahalli, Karnataka, he served as Principal of National College for decades and was Vice-Chancellor of Bengaluru University. Famous for debunking the 'miracles' of Sathya Sai Baba through a public commission. Founded the Karnataka Rationalist Association. Rajyotsava Award 1975.",
          wikiUrl: "https://en.wikipedia.org/wiki/H._Narasimhaiah",
          birthYear: 1920,
          deathYear: 2005,
          birthPlace: "Harinahalli, Karnataka",
          bornInDistrict: false,
          notable: "Rationalist · National College Principal · Bengaluru University VC",
          source: "Wikipedia",
          active: true,
        },
        {
          districtId: did,
          name: "S. Nijalingappa",
          nameLocal: "ಎಸ್. ನಿಜಲಿಂಗಪ್ಪ",
          category: "Politician",
          bio: "Veteran freedom fighter and one of Karnataka's most influential politicians. Chief Minister of Karnataka (1956–58 and 1968–71) and President of the Indian National Congress (1968–69). Born in Chitradurga, he was a key figure in the reorganisation of Karnataka. Led the INC during the Indira Gandhi-Congress split of 1969.",
          photoUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2a/S._Nijalingappa.jpg/440px-S._Nijalingappa.jpg",
          photoCredit: "Wikimedia Commons",
          wikiUrl: "https://en.wikipedia.org/wiki/S._Nijalingappa",
          birthYear: 1902,
          deathYear: 2000,
          birthPlace: "Chitradurga, Karnataka",
          bornInDistrict: false,
          notable: "INC President · CM Karnataka · Freedom Fighter",
          source: "Wikipedia",
          active: true,
        },
        {
          districtId: did,
          name: "Jayamaala",
          nameLocal: "ಜಯಮಾಲ",
          category: "Artist",
          bio: "Veteran Kannada actress, author and Rajya Sabha MP (2016–2022). Born in Bengaluru, she acted in over 200 Kannada films opposite Dr. Rajkumar and Vishnuvardhan. Known for her strong on-screen presence. Won Filmfare Kannada Lifetime Achievement Award and Rajyotsava Award.",
          wikiUrl: "https://en.wikipedia.org/wiki/Jayamala_(actress)",
          birthYear: 1958,
          birthPlace: "Bengaluru, Karnataka",
          bornInDistrict: true,
          notable: "200+ Kannada films · Rajya Sabha MP · Rajyotsava Award",
          source: "Wikipedia",
          active: true,
        },
        {
          districtId: did,
          name: "Infosys (Institution)",
          nameLocal: "ಇನ್ಫೋಸಿಸ್",
          category: "Entrepreneur",
          bio: "India's second-largest IT company, founded in 1981 by N.R. Narayana Murthy and six co-founders with $250 capital. Headquartered at Electronics City, Bengaluru, Infosys employs 330,000+ people globally and generates annual revenue exceeding $18 billion. Listed on NYSE and BSE. Credited with making Bengaluru the 'Silicon Valley of India'.",
          wikiUrl: "https://en.wikipedia.org/wiki/Infosys",
          birthYear: 1981,
          birthPlace: "Bengaluru, Karnataka",
          bornInDistrict: true,
          notable: "IT Giant · $18B revenue · 330,000 employees",
          source: "Wikipedia",
          active: true,
        },
        {
          districtId: did,
          name: "Smriti Mandhana",
          nameLocal: "ಸ್ಮೃತಿ ಮಂಧಾನ",
          category: "Sportsperson",
          bio: "India's premier women's cricketer and ICC Women's Cricketer of the Year (2018, 2021). Born in Mumbai but representing Karnataka in domestic cricket. Left-handed opener known for elegant strokeplay. Deputy captain of India Women's cricket team. One of the highest-paid women cricketers globally.",
          photoUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6e/Smriti_Mandhana.jpg/440px-Smriti_Mandhana.jpg",
          photoCredit: "Wikimedia Commons",
          wikiUrl: "https://en.wikipedia.org/wiki/Smriti_Mandhana",
          birthYear: 1996,
          birthPlace: "Mumbai, Maharashtra",
          bornInDistrict: false,
          notable: "ICC Women's Cricketer 2018, 2021 · India Deputy Captain",
          source: "Wikipedia",
          active: true,
        },
        {
          districtId: did,
          name: "Rohan Bopanna",
          nameLocal: "ರೋಹನ್ ಬೋಪಣ್ಣ",
          category: "Sportsperson",
          bio: "India's most successful doubles tennis player and world number 1 in ATP doubles (2024). Born in Kodagu, raised in Bengaluru, he became the oldest world No. 1 at age 43. Won the Australian Open doubles title in 2024. Former ATP Career-high singles ranking of 212. Known for his booming serve and net presence.",
          wikiUrl: "https://en.wikipedia.org/wiki/Rohan_Bopanna",
          birthYear: 1980,
          birthPlace: "Coorg, Karnataka",
          bornInDistrict: false,
          notable: "ATP Doubles World No.1 · Australian Open 2024",
          source: "Wikipedia",
          active: true,
        },
        {
          districtId: did,
          name: "Manohar Parrikar (DRDO-associated)",
          nameLocal: "ಮನೋಹರ್ ಪರ್ರಿಕರ್",
          category: "Politician",
          bio: "Former Defence Minister of India (2014–17) and Chief Minister of Goa. Associated with Bengaluru through DRDO's massive Defence Research complex which he championed. Bengaluru is home to DRDO's key aerospace, electronics, and defence systems labs including ADE, DARE, CAIR, and GTRE.",
          wikiUrl: "https://en.wikipedia.org/wiki/Manohar_Parrikar",
          birthYear: 1955,
          deathYear: 2019,
          birthPlace: "Mapusa, Goa",
          bornInDistrict: false,
          notable: "Defence Minister India · DRDO champion",
          source: "Wikipedia",
          active: true,
        },
        {
          districtId: did,
          name: "Dr. A.P.J. Abdul Kalam",
          nameLocal: "ಡಾ. ಎ.ಪಿ.ಜೆ. ಅಬ್ದುಲ್ ಕಲಾಮ್",
          category: "Scientist",
          bio: "India's 'Missile Man' and 11th President of India (2002–07). Though born in Rameswaram, Kalam's most critical work was at HAL (Hindustan Aeronautics Limited) and ISRO's Satellite Centre in Bengaluru, where he led the SLV-3 rocket programme and later Agni and Prithvi missile development. Bharat Ratna 1997.",
          photoUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6e/A._P._J._Abdul_Kalam.jpg/440px-A._P._J._Abdul_Kalam.jpg",
          photoCredit: "Wikimedia Commons",
          wikiUrl: "https://en.wikipedia.org/wiki/A._P._J._Abdul_Kalam",
          birthYear: 1931,
          deathYear: 2015,
          birthPlace: "Rameswaram, Tamil Nadu",
          bornInDistrict: false,
          notable: "Missile Man · 11th President · Bharat Ratna · ISRO/HAL Bengaluru",
          source: "Wikipedia",
          active: true,
        },
      ],
    });
    console.log("  ✓ Famous personalities: 25 seeded");
    console.log("  ✅ Bengaluru Urban leaders + personalities complete\n");
  } finally {
    if (standalone) await client.$disconnect();
  }
}

// ── Run standalone ──────────────────────────────────────
if (require.main === module) {
  const client = makeClient();
  seedBengaluruLeaders(client)
    .then(() => { console.log("Done."); process.exit(0); })
    .catch((e) => { console.error(e); process.exit(1); })
    .finally(() => client.$disconnect());
}
